config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  post '/upload/file', to: 'contacts#upload'

  namespace :api do
    namespace :v1 do
      resources :contacts
    end
  end
  root 'contacts#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	paginates_per 10
  belongs_to :user
	validates :phone,:presence => {:message => 'Just positive numbers without spaces are allowed'},
                      :numericality => true,
                      :length => { :minimum => 10, :maximum => 15 },
                      :uniqueness => true

    def self.create_contact(name,surname,phone,user_id)
    	#firstly check if exist
    	contact = Contact.find_by_phone(phone)
  		unless contact.present?
    		Contact.create(name: name, surname: surname, phone: phone, user_id: user_id)
  		end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts
end

app/controllers/api/v1/contacts_controller.rb
class Api::V1::ContactsController < ApplicationController

  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    # @contacts = Contact.all
    @contacts = current_user.contacts.order("created_at desc")
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    if @contact.save
        render "show.rabl"
    else
        render :json => [{:error => "Error occured record not created"}], :status => 500
        
    end
  end

  def update
    @contact.user_id = current_user.id
  	if @contact.update(contact_params)
          render "show.rabl"
  	else
          render :json => [{:error => "Error occured record not updated"}], :status => 500
	 end
  end

  def destroy
    @contact.destroy
    render 'index.rabl'
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.permit(:name, :surname, :phone, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  require 'nokogiri'
  require 'open-uri'
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = current_user.contacts.order("created_at desc").page(params[:page])
    # @contacts = Contact.all.order("created_at desc").page(params[:page])
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id
    if @contact.save
        redirect_to @contact, notice: 'Contact was successfully created.' 
    else
        render :new 
    end
  end

  def update
    @contact.user_id = current_user.id
  	if @contact.update(contact_params)
  	    redirect_to @contact, notice: 'Contact was successfully updated.' 
  	else
  	    render :edit
  	end
  end

  def destroy
    @contact.destroy
      redirect_to contacts_path, notice: 'Contact was successfully destroyed.' 
  end

  def upload
    uploaded_io = params[:xml_file]
    file_path = Rails.root.join('vendor', uploaded_io.original_filename) 

    File.open(file_path, 'wb') do |file|
      file.write(uploaded_io.read)
    end
    #parse xml
    doc = Nokogiri::XML(File.open(file_path))
    doc.css("contacts contact").each do |node|
      name = node.children.css("name").text
      surname = node.children.css("lastName").text
      phone = node.children.css("phone").text.gsub(/\s+/, "")
      user_id = current_user.id
      Contact.create_contact(name,surname,phone,user_id)
    end
    redirect_to contacts_path, notice: 'Contacts were successfully imported.'
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:name, :surname, :phone, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group">
    <label class="col-sm-2 control-label">Name:</label>
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control", placeholder: 'Name' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Surname:</label>
    <div class="col-sm-6">
      <%= f.text_field :surname, class: "form-control", placeholder: 'Surname' %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label">Phone:</label>
    <div class="col-sm-6">
      <%= f.text_field number_to_phone(:phone, :groupings => [4, 3, 3], :delimiter => "-") ,class: "form-control", placeholder: '(___) ___ ____' %>
      <!-- <input type="email"  id="inputEmail3" placeholder="Email"> -->
    </div>
  </div>
 <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-success btn-sm' %>
    </div>
  </div>

<% end %>

app/views/contacts/_upload_modal.html.erb
<div class="modal-body"> 
	
	 <%= form_tag({action: :upload}, multipart: true) do %>
  		<%= file_field_tag 'xml_file', style: 'margin: 5px !important;' %>
  		<%= submit_tag 'Upload', class: 'btn btn-default btn-xs', style: 'margin: 5px !important;' %>
	<% end %>
	 
</div>	
<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>

app/views/contacts/edit.html.erb
<h2 class="page-header">Editing Contact</h2>

<%= render 'form' %>

<%= link_to 'Show', @contact,  class: 'btn btn-primary btn-sm'%> |
<%= link_to 'Back', contacts_path, class: 'btn btn-primary btn-sm' %>

app/views/contacts/index.html.erb
<div class="col-md-12">
  <p id="notice"><%= notice %></p>

  <h2 class="page-header">Listing Contacts</h2>

  <p>You have <b><i><%= @contacts.total_count %></i></b> contacts.</p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
          <th>Name</th>
          <th>Surname</th>
          <th>Phone</th>
          <th></th>
          <th></th>
          <th></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.id %></td>
          <td><%= contact.name %></td>
          <td><%= contact.surname %></td>
          <td><%= number_to_phone(contact.phone, area_code: true)  %></td>
          <td><%= link_to 'Show', contact, class: 'btn btn-primary btn-sm'%></td>
          <td><%= link_to 'Edit', edit_contact_path(contact), class: 'btn btn-primary btn-sm' %></td>
          <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <%= paginate @contacts %>

  <br />
  <%= link_to 'New Contact', new_contact_path, class: 'btn btn-success btn-sm', style: 'margin:4px !important;' %>
  <br />
  <%= link_to "Import Contacts", "#upload_file_modal", :class => "btn btn-success btn-sm", "data-toggle" => "modal" , style: 'margin:4px !important;'%>
  
</div>

<div class="modal fade" id="upload_file_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Kapat</span></button>
        <h4 class="modal-title" id="myModalLabel"> Import Contacts From XML File </h4>
      </div>
        <%= render 'upload_modal' %>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="col-md-12">
	<h2 class="page-header">New Contact</h2>
		<%= render 'form' %>
	<br/>
	
	<%= link_to 'Back', contacts_path, class: 'btn btn-primary btn-sm' %>
</div>

app/views/contacts/show.html.erb
<div class="col-md-12">
	<p id="notice"><%= notice %></p>
	<h2 class="page-header">Contact Informations</h2>
	<p>
	  <strong>Name:</strong>
	  <%= @contact.name %>
	</p>

	<p>
	  <strong>Surname:</strong>
	  <%= @contact.surname %>
	</p>

	<p>
	  <strong>Phone:</strong>
	  <%=number_to_phone(@contact.phone, area_code: true) %>
	</p>


	<%= link_to 'Edit', edit_contact_path(@contact), class: 'btn btn-primary btn-sm' %> |
	<%= link_to 'Back', contacts_path, class: 'btn btn-primary btn-sm' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if user_signed_in? %>
		<div class = "row">
			<div class="container-fluid">
				<nav class="navbar navbar-default ">
				    <div class="navbar-header">
				      <a class="navbar-brand" href="/contacts" >
				       Ruby Challenge - Sample UI Application
				      </a>
					  <%#= link_to 'Log out',destroy_user_session_path, method: :delete,  %>
				    </div>
					<%= link_to 'Log out',destroy_user_session_path, method: :delete, style: "float: right; padding: 15px; font-size: 18px" %>
				</nav>
			</div>
		</div>
		
		<div class="col-md-12">
			<%= yield %>
		</div>
	<% else %>
		<div class="container" style="padding-top: 100px !important;">
			<%= yield  %>
		</div>
	<% end %>
</body>
</html>